# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'SSH - Ansible VM'
    playbookSourceRemoteMachine: 'agentMachine'
    playbookRootRemoteMachine: '$(System.DefaultWorkingDirectory)'
    playbookPathLinkedArtifactOnRemoteMachine: 'users.yml'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'agentMachine'
    inventoryFileLinkedArtifactOnRemoteMachine: 'azure_rm.yml'
    args: '--private-key ~/.ssh/ansible_rsa'